import { describe, it, expect } from 'vitest';
import { generateTypescript, generateJson, defaultFilename } from '../../src/codegen.js';
import { sampleAbi } from './fixtures.js';

describe('generateTypescript', () => {
  it('produces valid TypeScript with as const', () => {
    const output = generateTypescript('SP2P.nft-trait', sampleAbi);
    expect(output).toContain('export const abi =');
    expect(output).toContain('as const;');
  });

  it('includes the contract ID in a comment', () => {
    const output = generateTypescript('SP2P.nft-trait', sampleAbi);
    expect(output).toContain('// ABI for SP2P.nft-trait');
  });

  it('includes the generator attribution', () => {
    const output = generateTypescript('SP2P.nft-trait', sampleAbi);
    expect(output).toContain('// Generated by @satoshai/abi-cli');
  });

  it('contains the ABI data', () => {
    const output = generateTypescript('SP2P.nft-trait', sampleAbi);
    expect(output).toContain('"transfer"');
    expect(output).toContain('"get-owner"');
  });
});

describe('generateJson', () => {
  it('produces valid JSON', () => {
    const output = generateJson(sampleAbi);
    const parsed = JSON.parse(output);
    expect(parsed).toEqual(sampleAbi);
  });

  it('is pretty-printed', () => {
    const output = generateJson(sampleAbi);
    expect(output).toContain('\n');
    expect(output.split('\n').length).toBeGreaterThan(1);
  });
});

describe('defaultFilename', () => {
  it('derives filename from contract name for ts', () => {
    expect(defaultFilename('SP2P.nft-trait', 'ts')).toBe('nft-trait.ts');
  });

  it('derives filename from contract name for json', () => {
    expect(defaultFilename('SP2P.nft-trait', 'json')).toBe('nft-trait.json');
  });

  it('handles contract ID without dot', () => {
    expect(defaultFilename('standalone', 'ts')).toBe('standalone.ts');
  });
});
