import type { ClarityAbi } from '@stacks/transactions';

export interface GenerateTypescriptOptions {
  typed?: boolean;
}

/**
 * Generate a TypeScript file exporting the ABI as a const assertion.
 * When `typed` is true, adds `satisfies ClarityAbi` and a named `Abi` type alias.
 */
export function generateTypescript(
  contractId: string,
  abi: ClarityAbi,
  options: GenerateTypescriptOptions = {},
): string {
  const json = JSON.stringify(abi, null, 2);
  const lines: string[] = [];

  if (options.typed) {
    lines.push(`import type { ClarityAbi } from '@stacks/transactions';`);
    lines.push('');
  }

  lines.push(`// ABI for ${contractId}`);
  lines.push(`// Generated by @satoshai/abi-cli`);
  lines.push('');

  if (options.typed) {
    lines.push(`export const abi = ${json} as const satisfies ClarityAbi;`);
    lines.push('');
    lines.push('export type Abi = typeof abi;');
  } else {
    lines.push(`export const abi = ${json} as const;`);
  }

  lines.push('');
  return lines.join('\n');
}

/**
 * Generate formatted JSON output for the ABI.
 */
export function generateJson(abi: ClarityAbi): string {
  return JSON.stringify(abi, null, 2) + '\n';
}

/**
 * Derive a default output filename from a contract ID and format.
 */
export function defaultFilename(contractId: string, format: 'ts' | 'json'): string {
  const name = contractId.split('.').pop() ?? contractId;
  return `${name}.${format}`;
}
