import type { ClarityAbi } from '@stacks/transactions';

/**
 * Generate a TypeScript file exporting the ABI as a const assertion
 * with `satisfies ClarityAbi` for compile-time shape checking.
 */
export function generateTypescript(contractId: string, abi: ClarityAbi): string {
  const json = JSON.stringify(abi, null, 2);
  return [
    `import type { ClarityAbi } from '@stacks/transactions';`,
    '',
    `// ABI for ${contractId}`,
    `// Generated by @satoshai/abi-cli`,
    '',
    `export const abi = ${json} as const satisfies ClarityAbi;`,
    '',
    'export type Abi = typeof abi;',
    '',
  ].join('\n');
}

/**
 * Generate formatted JSON output for the ABI.
 */
export function generateJson(abi: ClarityAbi): string {
  return JSON.stringify(abi, null, 2) + '\n';
}

/**
 * Derive an output filename from an optional alias name or the contract ID.
 */
export function defaultFilename(contractId: string, format: 'ts' | 'json', nameOverride?: string): string {
  const name = nameOverride ?? contractId.split('.').pop() ?? contractId;
  return `${name}.${format}`;
}

/**
 * Convert a kebab-case (or already camelCase) string to camelCase.
 */
export function toCamelCase(name: string): string {
  return name.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

/**
 * Generate a barrel `index.ts` that re-exports all ABIs.
 *
 * Each entry maps to: `export { abi as <name>Abi } from './<filename>.js';`
 */
export function generateBarrel(entries: { name: string; filename: string }[]): string {
  const lines = entries
    .map(({ name, filename }) => {
      const exportName = `${toCamelCase(name)}Abi`;
      const modulePath = `./${filename.replace(/\.ts$/, '.js')}`;
      return `export { abi as ${exportName} } from '${modulePath}';`;
    });

  return [...lines, ''].join('\n');
}
