import type { ClarityAbi } from '@stacks/transactions';

/**
 * Generate a TypeScript file exporting the ABI as a const assertion
 * with `satisfies ClarityAbi` for compile-time shape checking.
 */
export function generateTypescript(contractId: string, abi: ClarityAbi): string {
  const json = JSON.stringify(abi, null, 2);
  return [
    `import type { ClarityAbi } from '@stacks/transactions';`,
    '',
    `// ABI for ${contractId}`,
    `// Generated by @satoshai/abi-cli`,
    '',
    `export const abi = ${json} as const satisfies ClarityAbi;`,
    '',
    'export type Abi = typeof abi;',
    '',
  ].join('\n');
}

/**
 * Generate formatted JSON output for the ABI.
 */
export function generateJson(abi: ClarityAbi): string {
  return JSON.stringify(abi, null, 2) + '\n';
}

/**
 * Derive a default output filename from a contract ID and format.
 */
export function defaultFilename(contractId: string, format: 'ts' | 'json'): string {
  const name = contractId.split('.').pop() ?? contractId;
  return `${name}.${format}`;
}
