import { describe, it, expect } from 'vitest';
import { generateTypescript, generateJson, defaultFilename } from '../../src/codegen.js';
import { sampleAbi } from './fixtures.js';

describe('generateTypescript', () => {
  it('produces valid TypeScript with as const', () => {
    const output = generateTypescript('SP2P.nft-trait', sampleAbi);
    expect(output).toContain('export const abi =');
    expect(output).toContain('as const;');
  });

  it('includes the contract ID in a comment', () => {
    const output = generateTypescript('SP2P.nft-trait', sampleAbi);
    expect(output).toContain('// ABI for SP2P.nft-trait');
  });

  it('includes the generator attribution', () => {
    const output = generateTypescript('SP2P.nft-trait', sampleAbi);
    expect(output).toContain('// Generated by @satoshai/abi-cli');
  });

  it('contains the ABI data', () => {
    const output = generateTypescript('SP2P.nft-trait', sampleAbi);
    expect(output).toContain('"transfer"');
    expect(output).toContain('"get-owner"');
  });
});

describe('generateTypescript with typed option', () => {
  it('includes import type and satisfies ClarityAbi when typed is true', () => {
    const output = generateTypescript('SP2P.nft-trait', sampleAbi, { typed: true });
    expect(output).toContain("import type { ClarityAbi } from '@stacks/transactions';");
    expect(output).toContain('as const satisfies ClarityAbi;');
    expect(output).toContain('export type Abi = typeof abi;');
  });

  it('places import before header comments', () => {
    const output = generateTypescript('SP2P.nft-trait', sampleAbi, { typed: true });
    const importIndex = output.indexOf('import type');
    const commentIndex = output.indexOf('// ABI for');
    expect(importIndex).toBeLessThan(commentIndex);
  });

  it('does not include satisfies when typed is false', () => {
    const output = generateTypescript('SP2P.nft-trait', sampleAbi, { typed: false });
    expect(output).not.toContain('satisfies');
    expect(output).not.toContain('import type');
    expect(output).not.toContain('export type Abi');
  });

  it('does not include satisfies when typed is omitted', () => {
    const output = generateTypescript('SP2P.nft-trait', sampleAbi);
    expect(output).not.toContain('satisfies');
  });
});

describe('generateJson', () => {
  it('produces valid JSON', () => {
    const output = generateJson(sampleAbi);
    const parsed = JSON.parse(output);
    expect(parsed).toEqual(sampleAbi);
  });

  it('is pretty-printed', () => {
    const output = generateJson(sampleAbi);
    expect(output).toContain('\n');
    expect(output.split('\n').length).toBeGreaterThan(1);
  });
});

describe('defaultFilename', () => {
  it('derives filename from contract name for ts', () => {
    expect(defaultFilename('SP2P.nft-trait', 'ts')).toBe('nft-trait.ts');
  });

  it('derives filename from contract name for json', () => {
    expect(defaultFilename('SP2P.nft-trait', 'json')).toBe('nft-trait.json');
  });

  it('handles contract ID without dot', () => {
    expect(defaultFilename('standalone', 'ts')).toBe('standalone.ts');
  });
});
