import { describe, it, expect } from 'vitest';
import { generateTypescript, generateJson, defaultFilename, toCamelCase, generateBarrel } from '../../src/codegen.js';
import { sampleAbi } from './fixtures.js';

describe('generateTypescript', () => {
  it('produces valid TypeScript with as const satisfies ClarityAbi', () => {
    const output = generateTypescript('SP2P.nft-trait', sampleAbi);
    expect(output).toContain('export const abi =');
    expect(output).toContain('as const satisfies ClarityAbi;');
  });

  it('includes import type for ClarityAbi', () => {
    const output = generateTypescript('SP2P.nft-trait', sampleAbi);
    expect(output).toContain("import type { ClarityAbi } from '@stacks/transactions';");
  });

  it('exports a named Abi type', () => {
    const output = generateTypescript('SP2P.nft-trait', sampleAbi);
    expect(output).toContain('export type Abi = typeof abi;');
  });

  it('places import before header comments', () => {
    const output = generateTypescript('SP2P.nft-trait', sampleAbi);
    const importIndex = output.indexOf('import type');
    const commentIndex = output.indexOf('// ABI for');
    expect(importIndex).toBeLessThan(commentIndex);
  });

  it('includes the contract ID in a comment', () => {
    const output = generateTypescript('SP2P.nft-trait', sampleAbi);
    expect(output).toContain('// ABI for SP2P.nft-trait');
  });

  it('includes the generator attribution', () => {
    const output = generateTypescript('SP2P.nft-trait', sampleAbi);
    expect(output).toContain('// Generated by @satoshai/abi-cli');
  });

  it('contains the ABI data', () => {
    const output = generateTypescript('SP2P.nft-trait', sampleAbi);
    expect(output).toContain('"transfer"');
    expect(output).toContain('"get-owner"');
  });
});

describe('generateJson', () => {
  it('produces valid JSON', () => {
    const output = generateJson(sampleAbi);
    const parsed = JSON.parse(output);
    expect(parsed).toEqual(sampleAbi);
  });

  it('is pretty-printed', () => {
    const output = generateJson(sampleAbi);
    expect(output).toContain('\n');
    expect(output.split('\n').length).toBeGreaterThan(1);
  });
});

describe('defaultFilename', () => {
  it('derives filename from contract name for ts', () => {
    expect(defaultFilename('SP2P.nft-trait', 'ts')).toBe('nft-trait.ts');
  });

  it('derives filename from contract name for json', () => {
    expect(defaultFilename('SP2P.nft-trait', 'json')).toBe('nft-trait.json');
  });

  it('handles contract ID without dot', () => {
    expect(defaultFilename('standalone', 'ts')).toBe('standalone.ts');
  });
});

describe('toCamelCase', () => {
  it('converts kebab-case to camelCase', () => {
    expect(toCamelCase('amm-pool')).toBe('ammPool');
  });

  it('converts multi-segment kebab-case', () => {
    expect(toCamelCase('nft-trait-v2')).toBe('nftTraitV2');
  });

  it('leaves already camelCase unchanged', () => {
    expect(toCamelCase('ammPool')).toBe('ammPool');
  });

  it('leaves single word unchanged', () => {
    expect(toCamelCase('token')).toBe('token');
  });
});

describe('generateBarrel', () => {
  it('generates re-exports with camelCase + Abi suffix', () => {
    const result = generateBarrel([
      { name: 'amm-pool', filename: 'amm-pool.ts' },
      { name: 'nft-trait', filename: 'nft-trait.ts' },
    ]);

    expect(result).toBe(
      [
        "export { abi as ammPoolAbi } from './amm-pool.js';",
        "export { abi as nftTraitAbi } from './nft-trait.js';",
        '',
      ].join('\n'),
    );
  });

  it('uses .js extension in import paths', () => {
    const result = generateBarrel([{ name: 'token', filename: 'token.ts' }]);
    expect(result).toContain("from './token.js'");
    expect(result).not.toContain('.ts');
  });

  it('handles single entry', () => {
    const result = generateBarrel([{ name: 'my-contract', filename: 'my-contract.ts' }]);
    expect(result).toBe("export { abi as myContractAbi } from './my-contract.js';\n");
  });
});
